gconv = [
                                                                                                                                                                                                                                                                                 L_stance*gamma1dot^2*sin(gamma1)
                                                                                                                                                                                                                                                                                -L_stance*gamma1dot^2*cos(gamma1)
                                                                                                                                                                                                                                                                                                                0
                             L_stance*sin(gamma1)*gamma1dot^2 - alpha2dot*((433*L_thigh*alpha2dot*cos(alpha2)*sin(gamma2))/1000 + (433*L_thigh*gamma2dot*cos(gamma2)*sin(alpha2))/1000) - gamma2dot*((433*L_thigh*alpha2dot*cos(gamma2)*sin(alpha2))/1000 + (433*L_thigh*gamma2dot*cos(alpha2)*sin(gamma2))/1000)
                           - L_stance*cos(gamma1)*gamma1dot^2 + alpha2dot*((433*L_thigh*alpha2dot*cos(alpha2)*cos(gamma2))/1000 - (433*L_thigh*gamma2dot*sin(alpha2)*sin(gamma2))/1000) + gamma2dot*((433*L_thigh*gamma2dot*cos(alpha2)*cos(gamma2))/1000 - (433*L_thigh*alpha2dot*sin(alpha2)*sin(gamma2))/1000)
                                                                                                                                                                                                                                                                       (433*L_thigh*alpha2dot^2*sin(alpha2))/1000
                            L_stance*sin(gamma1)*gamma1dot^2 - alpha2dot*(L_thigh*alpha2dot*cos(alpha2)*sin(gamma2) + L_thigh*gamma2dot*cos(gamma2)*sin(alpha2)) - gamma2dot*(L_thigh*alpha2dot*cos(gamma2)*sin(alpha2) + L_thigh*gamma2dot*cos(alpha2)*sin(gamma2)) - (433*L_shank*gamma3dot^2*sin(gamma3))/1000
                          - L_stance*cos(gamma1)*gamma1dot^2 + (433*L_shank*cos(gamma3)*gamma3dot^2)/1000 + alpha2dot*(L_thigh*alpha2dot*cos(alpha2)*cos(gamma2) - L_thigh*gamma2dot*sin(alpha2)*sin(gamma2)) + gamma2dot*(L_thigh*gamma2dot*cos(alpha2)*cos(gamma2) - L_thigh*alpha2dot*sin(alpha2)*sin(gamma2))
                                                                                                                                                                                                                                                                                  L_thigh*alpha2dot^2*sin(alpha2)
  L_stance*sin(gamma1)*gamma1dot^2 - L_shank*sin(gamma3)*gamma3dot^2 - alpha2dot*(L_thigh*alpha2dot*cos(alpha2)*sin(gamma2) + L_thigh*gamma2dot*cos(gamma2)*sin(alpha2)) - gamma2dot*(L_thigh*alpha2dot*cos(gamma2)*sin(alpha2) + L_thigh*gamma2dot*cos(alpha2)*sin(gamma2)) - (L_foot*gamma4dot^2*cos(gamma4))/2
- L_stance*cos(gamma1)*gamma1dot^2 + L_shank*cos(gamma3)*gamma3dot^2 + alpha2dot*(L_thigh*alpha2dot*cos(alpha2)*cos(gamma2) - L_thigh*gamma2dot*sin(alpha2)*sin(gamma2)) + gamma2dot*(L_thigh*gamma2dot*cos(alpha2)*cos(gamma2) - L_thigh*alpha2dot*sin(alpha2)*sin(gamma2)) - (L_foot*gamma4dot^2*sin(gamma4))/2
                                                                                                                                                                                                                                                                                  L_thigh*alpha2dot^2*sin(alpha2)
 
];
